package capstone1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import java.sql.*;
/**
 *
 * @author angel
 */
//private UserLogin UsLogin = new UserLogin;
public class LogIn extends javax.swing.JFrame {

    private UserLogin ul = new UserLogin();
    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        aboutBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        aboutBtnn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Cartel");
        setMinimumSize(new java.awt.Dimension(1068, 600));
        setPreferredSize(new java.awt.Dimension(1068, 600));
        setResizable(false);
        ContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/The Cartel.png"))); // NOI18N
        ContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 590, 140));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 150, 60));

        aboutBtn.setBackground(new java.awt.Color(102, 102, 102));
        aboutBtn.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        aboutBtn.setForeground(new java.awt.Color(255, 255, 255));
        aboutBtn.setText("About the game");
        aboutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutBtnActionPerformed(evt);
            }
        });
        ContentPane().add(aboutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 150, 60));

        exitBtn.setBackground(new java.awt.Color(102, 102, 102));
        exitBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        ContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, 150, 60));

        loginBtn.setBackground(new java.awt.Color(102, 102, 102));
        loginBtn.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Log-in");
        loginBtn.setBorder(null);
        loginBtn.setBorderPainted(false);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        ContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 150, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mafiacig.jpg"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(1060, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(1060, 400));
        ContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 570));

        aboutBtnn.setBackground(new java.awt.Color(102, 102, 102));
        aboutBtnn.setFont(new java.awt.Font("MS UI Gothic", 0, 18)); // NOI18N
        aboutBtnn.setForeground(new java.awt.Color(255, 255, 255));
        aboutBtnn.setText("About the game");
        aboutBtnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        ContentPane().add(aboutBtnn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 150, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
     logrun();  // TODO add your handling code here:
     
    }//GEN-LAST:event_loginBtnActionPerformed
       
    private void aboutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBtnActionPerformed
     instrun();   // TODO add your handling code here:
    }//GEN-LAST:event_aboutBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }
    public void logrun(){
        
    }
    public void instrun(){
        JFrame instframe = new JFrame("About the game");
        JPanel instpanel = new JPanel();
        instframe.setSize(400,600);
        
        JTextArea instinfo = new JTextArea(30,20); 
        instinfo.setText("BLEH");
        //instinfo.seta
        instinfo.setEditable(false);
      
        instframe.add(instpanel);
        instpanel.add(instinfo);
        
        instframe.setLocationRelativeTo(null);
        instframe.setVisible(true);
        instframe.setResizable(false);
        this.pack();
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutBtn;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton aboutBtnn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}

//DATABSE, LOGIN.LOGOUT, MULTIPLE USER, REGISTER, SERVER
