/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capstone1;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout; 

/**
 *
 * @author angel
 */
public class RegisterFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterFrame
     */
    MainFrame parent;
    
    public RegisterFrame(MainFrame parent){
        this.parent = parent;
        initComponents();
        JLabel mafiaCig = new JLabel();
        JLabel bgLabel = new JLabel();
        
        setTitle("The Cartel");
        setSize(1068,600);
        setLocation(200,100);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setVisible(true);
        setResizable(false);
    }
    public RegisterFrame() {
        initComponents();
    }
    
    private void createUser() throws SQLException, ClassNotFoundException{
        if(nameField.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Name Field" + "is empty", "Name Required", JOptionPane.ERROR_MESSAGE);
        }
        String query = "Insert into Account(Name, Username, Password, EmailAddress)" +
                   "Values " + "(" + nameField.getText() + "," 
                             + usernameField.getText() + "," 
                             + passField.getPassword()+ "," 
                             + emailField.getText() + ");";         
        Statement stmt = null;
        String Username = "CapstoneCartel";
        String Password = "thisissupersecure";
        
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String dbconn = "jdbc:sqlserver://172.18.53.128, 49171\\SQLEXPRESS database=Capstone"; //
        //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); //connecting to the database
        //String dbconn = "jdbc:sqlserver://172.18.53.128,49171"; //
        Connection conn = DriverManager.getConnection(dbconn, Username, Password);
        stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,
                ResultSet.CONCUR_UPDATABLE);
      	ResultSet rset = stmt.executeQuery(query);
        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNLabel = new javax.swing.JLabel();
        userLabel1 = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passLabel1 = new javax.swing.JLabel();
        regButton = new javax.swing.JButton();
        backLog = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        emailField = new javax.swing.JTextField();
        theCartelLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Cartel");
        getContentPane().setLayout(null);

        userNLabel.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        userNLabel.setText("Username:");
        getContentPane().add(userNLabel);
        userNLabel.setBounds(550, 130, 140, 60);

        userLabel1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        userLabel1.setText("Name:");
        getContentPane().add(userLabel1);
        userLabel1.setBounds(550, 70, 140, 60);

        emailLabel.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        emailLabel.setText("Email:");
        getContentPane().add(emailLabel);
        emailLabel.setBounds(550, 230, 180, 80);

        passLabel1.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        passLabel1.setText("Password:");
        getContentPane().add(passLabel1);
        passLabel1.setBounds(550, 180, 180, 80);

        regButton.setText("Create");
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });
        getContentPane().add(regButton);
        regButton.setBounds(830, 330, 120, 50);

        backLog.setText("Back to Login");
        backLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLogActionPerformed(evt);
            }
        });
        getContentPane().add(backLog);
        backLog.setBounds(830, 420, 120, 30);

        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameFieldusernamePressed(evt);
            }
        });
        getContentPane().add(nameField);
        nameField.setBounds(700, 80, 250, 30);

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        usernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameFieldusernamePressed(evt);
            }
        });
        getContentPane().add(usernameField);
        usernameField.setBounds(700, 140, 250, 30);

        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        passField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passFieldpasswordPressed(evt);
            }
        });
        getContentPane().add(passField);
        passField.setBounds(700, 200, 250, 30);

        emailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailFieldusernamePressed(evt);
            }
        });
        getContentPane().add(emailField);
        emailField.setBounds(700, 260, 250, 30);

        theCartelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/The Cartel.png"))); // NOI18N
        getContentPane().add(theCartelLabel);
        theCartelLabel.setBounds(420, 420, 650, 180);

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mafiacig.jpg"))); // NOI18N
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 1068, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
        try{
            createUser();
        } catch(SQLException e){
            System.out.print("SQL Fail");
        } catch (ClassNotFoundException ex) {
            System.out.print("Class Not Found");
        }
        
    }//GEN-LAST:event_regButtonActionPerformed

    private void usernameFieldusernamePressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameFieldusernamePressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER)
           passField.requestFocus();
    }//GEN-LAST:event_usernameFieldusernamePressed

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void passFieldpasswordPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFieldpasswordPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            emailField.requestFocus();
    }//GEN-LAST:event_passFieldpasswordPressed

    private void nameFieldusernamePressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldusernamePressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            usernameField.requestFocus();
    }//GEN-LAST:event_nameFieldusernamePressed

    private void emailFieldusernamePressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFieldusernamePressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            try{
                createUser();
            } catch (SQLException ex) {
            Logger.getLogger(RegisterFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //catch {(SQL EXception e)
        //    }
    }//GEN-LAST:event_emailFieldusernamePressed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void backLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLogActionPerformed
        parent.launchUserLogin();
    }//GEN-LAST:event_backLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backLog;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel1;
    private javax.swing.JButton regButton;
    private javax.swing.JLabel theCartelLabel;
    private javax.swing.JLabel userLabel1;
    private javax.swing.JLabel userNLabel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}

